export const IS_DEV = !import.meta.env.VITE_VIVERSE_APP_ID;

export const SAMPLE_LEADERBOARD = IS_DEV
  ? {
      ranking: [
        { name: "Wawa Sensei", rank: 0, value: 123 },
        { name: "John Doe", rank: 1, value: 52 },
        { name: "Max Verstappen", rank: 2, value: 42 },
        { name: "Alice Chen", rank: 3, value: 41 },
        { name: "Bob Wilson", rank: 4, value: 40 },
        { name: "Carlos Rodriguez", rank: 5, value: 39 },
        { name: "Diana Thompson", rank: 6, value: 38 },
        { name: "Ethan Brown", rank: 7, value: 37 },
        { name: "Fiona Garcia", rank: 8, value: 36 },
        { name: "George Martinez", rank: 9, value: 35 },
        { name: "Hannah Davis", rank: 10, value: 34 },
        { name: "Isaac Miller", rank: 11, value: 33 },
        { name: "Julia Anderson", rank: 12, value: 32 },
        { name: "Kevin Taylor", rank: 13, value: 31 },
        { name: "Laura Moore", rank: 14, value: 30 },
        { name: "Michael Johnson", rank: 15, value: 29 },
        { name: "Nancy White", rank: 16, value: 28 },
        { name: "Oliver Harris", rank: 17, value: 27 },
        { name: "Patricia Clark", rank: 18, value: 26 },
        { name: "Quinn Lewis", rank: 19, value: 25 },
        { name: "Rachel Walker", rank: 20, value: 24 },
        { name: "Samuel Hall", rank: 21, value: 23 },
        { name: "Tina Allen", rank: 22, value: 22 },
        { name: "Uma Young", rank: 23, value: 21 },
        { name: "Victor King", rank: 24, value: 20 },
        { name: "Wendy Wright", rank: 25, value: 19 },
        { name: "Xavier Scott", rank: 26, value: 18 },
        { name: "Yuki Torres", rank: 27, value: 17 },
        { name: "Zachary Green", rank: 28, value: 16 },
        { name: "Amy Baker", rank: 29, value: 15 },
        { name: "Brian Hill", rank: 30, value: 14 },
        { name: "Cathy Adams", rank: 31, value: 13 },
        { name: "David Nelson", rank: 32, value: 12 },
        { name: "Emma Carter", rank: 33, value: 11 },
        { name: "Frank Mitchell", rank: 34, value: 10 },
        { name: "Grace Roberts", rank: 35, value: 9 },
        { name: "Henry Turner", rank: 36, value: 8 },
        { name: "Iris Campbell", rank: 37, value: 7 },
        { name: "Jack Parker", rank: 38, value: 6 },
        { name: "Karen Evans", rank: 39, value: 5 },
        { name: "Leo Edwards", rank: 40, value: 5 },
        { name: "Maria Collins", rank: 41, value: 5 },
        { name: "Nathan Stewart", rank: 42, value: 4 },
        { name: "Olivia Morris", rank: 43, value: 4 },
        { name: "Peter Rogers", rank: 44, value: 4 },
        { name: "Quincy Reed", rank: 45, value: 4 },
        { name: "Rose Cook", rank: 46, value: 3 },
        { name: "Steve Morgan", rank: 47, value: 3 },
        { name: "Tara Bell", rank: 48, value: 3 },
        { name: "Ulrich Murphy", rank: 49, value: 3 },
        { name: "Violet Bailey", rank: 50, value: 3 },
        { name: "William Cooper", rank: 51, value: 2 },
        { name: "Xena Richardson", rank: 52, value: 2 },
        { name: "Yasmin Cox", rank: 53, value: 2 },
        { name: "Zoe Ward", rank: 54, value: 2 },
        { name: "Alex Peterson", rank: 55, value: 2 },
        { name: "Bella Gray", rank: 56, value: 2 },
        { name: "Chris James", rank: 57, value: 2 },
        { name: "Donna Watson", rank: 58, value: 1 },
        { name: "Eric Brooks", rank: 59, value: 1 },
        { name: "Felicity Kelly", rank: 60, value: 1 },
        { name: "Gavin Sanders", rank: 61, value: 1 },
        { name: "Holly Price", rank: 62, value: 1 },
        { name: "Ian Bennett", rank: 63, value: 1 },
        { name: "Jessica Wood", rank: 64, value: 1 },
        { name: "Kyle Barnes", rank: 65, value: 1 },
        { name: "Linda Ross", rank: 66, value: 1 },
        { name: "Mason Henderson", rank: 67, value: 1 },
        { name: "Nina Coleman", rank: 68, value: 1 },
        { name: "Oscar Jenkins", rank: 69, value: 1 },
        { name: "Penny Powell", rank: 70, value: 1 },
        { name: "Quentin Long", rank: 71, value: 1 },
        { name: "Rita Patterson", rank: 72, value: 1 },
        { name: "Simon Hughes", rank: 73, value: 1 },
        { name: "Tiffany Flores", rank: 74, value: 1 },
        { name: "Uriel Washington", rank: 75, value: 1 },
        { name: "Vera Butler", rank: 76, value: 1 },
        { name: "Walter Simmons", rank: 77, value: 1 },
        { name: "Xander Foster", rank: 78, value: 1 },
        { name: "Yolanda Gonzalez", rank: 79, value: 1 },
        { name: "Zara Bryant", rank: 80, value: 1 },
        { name: "Adam Alexander", rank: 81, value: 1 },
        { name: "Beth Russell", rank: 82, value: 1 },
        { name: "Carl Griffin", rank: 83, value: 1 },
        { name: "Diane Diaz", rank: 84, value: 1 },
        { name: "Edward Hayes", rank: 85, value: 1 },
        { name: "Faith Myers", rank: 86, value: 1 },
        { name: "Gordon Ford", rank: 87, value: 1 },
        { name: "Heather Hamilton", rank: 88, value: 1 },
        { name: "Ivan Graham", rank: 89, value: 1 },
        { name: "Jane Sullivan", rank: 90, value: 1 },
        { name: "Keith Wallace", rank: 91, value: 1 },
        { name: "Luna Woods", rank: 92, value: 1 },
        { name: "Marcus Cole", rank: 93, value: 1 },
        { name: "Nora West", rank: 94, value: 1 },
        { name: "Owen Jordan", rank: 95, value: 1 },
        { name: "Paula Owens", rank: 96, value: 1 },
        { name: "Quinn Reynolds", rank: 97, value: 1 },
        { name: "Ryan Fisher", rank: 98, value: 1 },
        { name: "Sophia Ellis", rank: 99, value: 1 },
      ],
    }
  : undefined;

export const SAMPLE_AVATAR = IS_DEV
  ? [
      {
        headIconUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/9b3c01539a04bd7b11dedeb686c0b6af2a110de2d833e263b783514a1881311d7d23/files?filetype=headicon",
        id: 162432,
        vrmUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/9b3c01539a04bd7b11dedeb686c0b6af2a110de2d833e263b783514a1881311d7d23/files?filetype=model&lod=original",
      },
      {
        headIconUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/d77c515d7223fef4135d092b8421c7f2f9b6ed1ec932688e9aba51fa85af1340e370/files?filetype=headicon",
        id: 162431,
        vrmUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/d77c515d7223fef4135d092b8421c7f2f9b6ed1ec932688e9aba51fa85af1340e370/files?filetype=model&lod=basic",
      },
      {
        headIconUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/7794b8b1e77831d9bdc79df989c39a60a1dbd15170a4c0e5356af59536e55680b1ae/files?filetype=headicon",
        id: 172141,
        vrmUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/7794b8b1e77831d9bdc79df989c39a60a1dbd15170a4c0e5356af59536e55680b1ae/files?filetype=model&lod=original",
      },
    ]
  : [
      {
        headIconUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/9b3c01539a04bd7b11dedeb686c0b6af2a110de2d833e263b783514a1881311d7d23/files?filetype=headicon",
        id: 162432,
        vrmUrl:
          "https://avatar.viverse.com/api/meetingareaselector/v2/newgenavatar/avatars/9b3c01539a04bd7b11dedeb686c0b6af2a110de2d833e263b783514a1881311d7d23/files?filetype=model&lod=original",
      },
    ];


